//
// Created by dell on ٣٠/٠٥/٢٠٢٢.
//

#ifndef GRAPHICSPROJECT_INPUT_H
#define GRAPHICSPROJECT_INPUT_H
enum METHOD {NOINPUT, DIRECT_CIRCLE,POLAR_CIRCLE,ITERATIVE_POLAR_CIRCLE,MIDPOINT_CIRCLE,MODIFIED_MIDPOINT_CIRCLE
,DDA_LINE,MIDPOINT_LINE,PARAMETRIC_LINE, ELIPSE_DIRECT,MIDPOINT_ELIPSE, POLAR_ELIPSE,RED,BLACK,GREEN,BLUE,YELLOW,PURPLE,
CLIPPING_WINDOW_POINT,CLIPPING_WINDOW_LINE,CLIPPING_CIRCLE_POINT,CLIPPING_CIRCLE_LINE,CLIPPING_WINDOW_POLYGON,
    FILLING_CIRCLE_LINES, FILLING_CIRCLE_circles, FILLING_RECTANGLE_BEZIER, FILLING_SQUARE_HERMIT, FILLING_R_FLOODFILL_R,FILLING_NR_FLOODFILL_R,
    FILLING_R_FLOODFILL_C,FILLING_NR_FLOODFILL_C,FILLING_R_FLOODFILL_E,FILLING_NR_FLOODFILL_E,FILLING_GENERAL_POLYGON,QUARTER_1,QUARTER_2,
    QUARTER_3,QUARTER_4,FILLING_CONVEX,CLEAR,CARDINAL_SPLINE, OPEN_FILE_BUTTON, Save_FILE_BUTTON};
#endif //GRAPHICSPROJECT_INPUT_H
